package com.shashi.minipay.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.time.Instant;
import java.util.UUID;

/**
 * User JPA Entity representing application users.
 *
 * KEY CONCEPTS:
 * - @Entity: Marks this class as a JPA entity (maps to database table)
 * - @Table: Specifies the table name in database
 * - @Id + @GeneratedValue: Primary key with UUID auto-generation
 * - @Enumerated: Maps UserRole enum to database as STRING
 * - @Column: Defines column properties (nullable, unique, length, etc)
 * - Getter/Setter: Generated by Lombok to reduce boilerplate
 *
 * SCHEMA CONSIDERATIONS:
 * - username, email are unique to prevent duplicate users
 * - passwordHash stores bcrypt-hashed passwords (never plain text!)
 * - createdAt, updatedAt track record lifecycle
 * - role determines authorization level
 */
@Entity
@Table(name = "users", uniqueConstraints = {
        @UniqueConstraint(columnNames = "username", name = "uk_users_username"),
        @UniqueConstraint(columnNames = "email", name = "uk_users_email")
})
@Getter
@Setter
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @Column(nullable = false, unique = true, length = 50)
    private String username;

    @Column(nullable = false, unique = true, length = 255)
    private String email;

    /**
     * Password hash using BCrypt (never store plain passwords!)
     * BCrypt hashes are ~60 characters
     */
    @Column(nullable = false, length = 100)
    private String passwordHash;

    /**
     * Role determines what actions user can perform
     * Stored as string in database (CUSTOMER or ADMIN)
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private UserRole role;

    @Column(nullable = false)
    private Instant createdAt;

    @Column(nullable = false)
    private Instant updatedAt;
}
